version: '3.1'

volumes:
    local_prometheus_data: {}
    central_prometheus_data: {}
    influxdb_data: {}

services:

  local-prometheus:
    image: prom/prometheus:v2.0.0
    volumes:
      - ../prometheus/local/:/etc/prometheus/
      - local_prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    restart: always
    deploy:
      mode: global

  central-prometheus:
    image: prom/prometheus:v2.0.0
    volumes:
      - ../prometheus/central/:/etc/prometheus/
      - central_prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - 9000:9090
      - 9092:9092
    links:
      - alertmanager:alertmanager
    restart: always
    deploy:
      mode: global

  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - ../alertmanager/:/etc/alertmanager/
    restart: always
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    deploy:
      mode: global
  
  ts-app:    
    build: 
     context: ../app
     dockerfile: Dockerfile
    image: ts-app
    container_name: deploy_app
    ports:
      - 8081:8080
    links:
      - local-prometheus:local-prometheus

  adapter:
    build:
     context: ../adapter
     dockerfile: Dockerfile
    image: adapter
    restart: always
    environment:
      - INFLUXDB=prometheus
      - INFLUXDB_RP=autogen
      - INFLUXDB_URL=http://influxdb:8086
    ports:
      - 9201:9201
    environment:
      - INFLUXDB_PW=prom
    links:
      - influxdb:influxdb
    deploy:
      mode: global
  
  influxdb:
    image: influxdb:1.3.5
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_DB=prometheus
      - INFLUXDB_USER=prom
      - INFLUXDB_USER_PASSWORD=prom
    volumes:
      - influxdb_data:/var/lib/influxdb
    restart: always
    command: -config /etc/influxdb/influxdb.conf
    deploy:
      mode: global
