version: '3.1'

volumes:
    local_prometheus_data: {}
    central_prometheus_data: {}
    postgres_data: {}

services:
  pgdb:
    image: timescale/pg_prometheus
    ports:
      - 5433:5432
    restart: always
    deploy:
      mode: global
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=password

  local-prometheus:
    image: prom/prometheus:v2.0.0
    volumes:
      - ../prometheus/local/:/etc/prometheus/
      - local_prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    restart: always
    deploy:
      mode: global

  central-prometheus:
    image: prom/prometheus:v2.0.0
    volumes:
      - ../prometheus/central/:/etc/prometheus/
      - central_prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - 9000:9090
      - 9092:9092
    links:
      - alertmanager:alertmanager
    restart: always
    deploy:
      mode: global

  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - ../alertmanager/:/etc/alertmanager/
    restart: always
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    deploy:
      mode: global
  
  ts-app:    
    build: 
     context: ../app
     dockerfile: Dockerfile
    image: ts-app
    container_name: deploy_app
    ports:
      - 8081:8080
    links:
      - local-prometheus:local-prometheus

  adapter:
    build:
     context: ../adapter
     dockerfile: Dockerfile
    image: adapter
    restart: always
    environment:
      - DB_HOST=pgdb
      - DB_PORT=5432
    ports:
      - 9201:9201
    links:
      - pgdb:pgdb
    deploy:
      mode: global
