version: '3.1'

volumes:
    prometheus_data: {}

services:

  prometheus:
    image: prom/prometheus:v2.0.0
    volumes:
      - ../prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    links:
      - alertmanager:alertmanager
    restart: always
    deploy:
      mode: global

  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - ../alertmanager/:/etc/alertmanager/
    restart: always
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    deploy:
      mode: global
  
  ts-app:    
    build: 
     context: ../app
     dockerfile: Dockerfile
    image: ts-app
    container_name: deploy_app
    ports:
      - 8080:8080
    links:
      - prometheus:prometheus
      - alertmanager:alertmanager

