# my global config
global:
  scrape_interval:     4s # Set the scrape interval to every 1 second. Default is every 1 minute.
  evaluation_interval: 4s # Evaluate rules every 1 second. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'ts-app-indonesia'

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
   - "alert.rules"

# Alertmanager configuration
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

remote_read:
        - url: "http://adapter:9201/read"

